config/routes.rb
Enclone::Application.routes.draw do
  resources :users, :except => [:index]
  resource :session, :only => [:new, :create, :destroy]
  resources :notebooks
  resources :notes
  resources :tags, :only => [:create, :index, :destroy, :show]

  root :to => "root#root"
end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
  attr_accessible :title, :user_id
  validates :title, :user_id, :presence => true

  belongs_to :user
  has_many :notes, :dependent => :destroy

end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  before_filter :require_current_user!
  respond_to :json, :html

  def index
    # if current_user.notebooks.any?
#       @notebook = current_user.notebooks.first
#       #@note = @notebook.notes.first if @notebook.notes.any?
#     else
#       @notebook = Notebook.create(
#       :user_id => current_user.id,
#       :title => "Default"
#       )
#       #@note = Note.new
#     end
#     @notes = @notebook.notes
    @notebooks = current_user.notebooks
    respond_with(@notebooks)

  end

  def create
    @notebook = Notebook.new(params[:notebook])
    @notebook.user_id = current_user.id
    @notes = @notebook.notes
    unless @notebook.save
      flash[:errors] = @notebook.errors.full_messages
    end

    render 'notebooks/index'
  end

  def show
    @notebook = Notebook.find(params[:id])
    @notes = @notebook.notes

    respond_with(@notes)
  end

  def new
  end

  def update
    @notebook = Notebook.find(params[:id])
    @notebook.update_attributes(params[:notebook])

    render :json => @notebook
  end

  def destroy
    @notebook = Notebook.find(params[:id])
    if current_user.notebooks.length == 1
      flash[:errors] = ["You must have at least one notebook"]
    else
      @notebook.destroy
      @notebook = current_user.notebooks.last
    end

    render :json => {}
  end

end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/views/notebooks/_new_notebook.html.erb
<form action="<%= notebooks_url %>" method="POST">
  <label for="notebook-title">
    <input type="text" name="notebook[title]">
  </label>

  <%= render './layouts/form_auth' %>
  <input type="submit" value="Create Notebook">
</form>

app/views/notebooks/_show.html.erb
<% notebook.notes.each do |note| %>
  <%= link_to note.title, note_url(note) %>
  notebook id: <%= note.notebook_id %><br>
  <%= button_to "Delete", note_url(note), method: :delete %>
<% end  %>

app/views/notebooks/new.html.erb
<%= render 'new_notebook' %>

<form action="<%= notebooks_url %>" method="POST">
  <label for="notebook-title">
    <input type="text" name="notebook[title]">
  </label>

  <%= render './layouts/form_auth' %>
  <input type="submit" value="Create Notebook">
</form>

app/views/notebooks/old_index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>title</title>
    <link rel="stylesheet" href="style.css">
    <script src="script.js"></script>
    <style>

      .group:after {
        content: "";
        display: block;
        clear: both;
      }
      nav {
        width: 98%;
        background-color: green;
        border: 1px solid black;
      }

      li {
        list-style: none;
      }
      nav li {
        float: right;
        text-align: center;
      }
      .app-header {
        width: 100%;
        background: orange;
      }
      header button {
        float: left;
      }
      #main-content {
        width: 98%;
        height: 100%;
        margin: auto;
      }
      #main-content > div {
        height: 900px;
      }
      div.notebooks-sidebar {
        width: 10%;
        float: left;
        background: lightgray;
      }
      div.notes-sidebar {
        width: 14%;
        float: left;
        border-left: 1px solid gray;
        background: lightgray;
      }

      div.notes-sidebar ul {
        margin: auto;
      }
      div.note-creation-area {
        width: 74%;
        float: left;
        background: lightgray;
        border-left: 1px solid gray;
      }

      .center {
        margin: auto;
      }


    </style>

  </head>
  <body>
    <nav class="group">
        <div class="Title">Enclone</div>
        <ul id="nav-list">
          <li>Signed In?</li>
          <li>Account Settings</li>
        </ul>
    </nav>
  <header class="app-header group">
    <!-- <button id="search">Search</button> -->


  </header>

  <div id="main-content" class="group">
    <div class="notebooks-sidebar">
      <header class="notebooks-sidebar">Notebooks</header>
      <ul class="notebooks-list">
        <form action="<%= notebooks_url %>", method="POST">
          <label for="new-notebook-title">
            <input type="text" name="notebook[title]">
          </label>
          <%= render './layouts/form_auth' %>
          <input type="submit" value="Create Notebook">
        </form>
        <% current_user.notebooks.each do |notebook| %>
          <li><%= link_to notebook.title, notebook_url(notebook) %></li>
          <%= button_to "Delete", notebook_url(notebook), method: :delete %>
        <% end %>
      </ul>
      Tags
      <ul >
        <%= render './tags/index', :tags => current_user.tags %>
      </ul>
    </div>
    <div class="notes-sidebar">
      <header class="notes-sidebar"><%= @notebook.title %></header>
      <ul class="note-list">
        <!-- either a notebook/all notes/or notes by tag -->
        <!-- if notebook show was clicked then next line-->
        <%= render './notes/index', :notes => @notes %>
        <!-- if tag was clicked, render tag show page -->
        <!-- if all notes was clicked render either notes index
        or user.notes -->
      </ul>
    </div>
    <div class="note-creation-area">
      <a href="/notes/new/?notebook_id=<%= @notebook.id %>">Create New Note</a>
      <% if !!@note %>
        <%= render './notes/show', :note => @note, :notebook => @notebook, :tags => @note.tags %>
      <% end %>
    </div>
  </div>
  </body>
</html>