config/routes.rb
Enclone::Application.routes.draw do
  resources :users, :except => [:index]
  resource :session, :only => [:new, :create, :destroy]
  resources :notebooks
  resources :notes
  resources :tags, :only => [:create, :index, :destroy, :show]

  root :to => "root#root"
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :title, :body, :notebook_id, :tag_ids
  validates :notebook_id, :presence => true

  belongs_to :notebook
  #has_many :tags, dependent: :destroy
  belongs_to :user
  has_many :taggings
  has_many :tags, :through => :taggings

  def tag_names
    self.tags.map { |tag| tag.title }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :email, :session_token
  attr_reader :password

  before_validation :ensure_session_token
  validates :password_digest, :session_token, :email, :presence => true
  validates :email, :uniqueness => true

  has_many :notebooks
  has_many :tags
  has_many :notes, through: :notebooks

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save
    return self.session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def ensure_session_token
    self.session_token ||= reset_session_token
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :require_current_user!
  respond_to :html, :json

  def new
    if params[:notebook_id]
      @notebook = Notebook.find(params[:notebook_id])
    else
      @notebook = Notebook.create(
      :user_id => current_user_id,
      :title => "Default"
      )
    end

    @note = Note.create(
    :notebook_id => @notebook.id,
    :body => "",
    :title => "Untitled"
    )
    @notes = @notebook.notes
    render 'notebooks/index'
  end

  def index
    @notes = current_user.notes
    respond_with(@notes)
  end

  def create
    @note = Note.new(params[:note])
    #@notebook = Notebook.find(params[:note][:notebook_id])
    #@notes = @notebook.notes
    @note.title = "Untitled"
    @note.save!
    flash[:errors] = @note.errors.full_messages unless @note.save

    render :json => @note
  end

  def show
    # @note = Note.find(params[:id])
#     @notebook = Notebook.find(@note.notebook_id)
#     @notes = @notebook.notes
#
#     render 'notebooks/index'
    @note = Note.find(params[:id])
    respond_with(@note)
  end

  def update
    @note = Note.find(params[:id])
    @note.update_attributes(params[:note])
    @notebook = Notebook.find(@note.notebook_id)
    @notes = @notebook.notes
    # if params[:tag][:title].length > 0
#       Tag.create(
#         :user_id => current_user.id,
#         :note_id => @note.id,
#         :title => params[:tag][:title]
#       )
#     end

    render :json => @note
  end

  def destroy
    unwanted_note = Note.find(params[:id])
    @notebook = unwanted_note.notebook
    unwanted_note.destroy
    @notes = @notebook.notes
    # @note = Note.create(
#       :notebook_id => @notebook.id,
#       :title => "Untitled",
#     )

    render 'notebooks/index'
  end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_index.html.erb
<% notes.each do |note| %>
  <%= link_to note.title, note_url(note) %>
  notebook id: <%= note.notebook_id %><br>
  <%= button_to "Delete", note_url(note), method: :delete %>
<% end  %>

app/views/notes/_new.html.erb
<form action="<%= notes_url %>" method="POST">
  <label for="note-title">
    <input type="text" name="note[title]" value="Untitled">
  </label>

  <label for="note-body">
    <textarea name="note[body]"></textarea>
  </label>
  <input type="hidden" name="note[notebook_id]" value="<%= notebook.id %>"></input>
  <%= render "./layouts/form_auth" %>
  <input type="submit" value="Save Note"></input>
</form>

app/views/notes/_show.html.erb
<% note ||= nil %>
<%= @notebook.title %>


<!-- <% if !note.nil? %> -->

  <%= note.title %><br><%= note.body %>

  <form action="/notes/<%= note.id %>" method="POST">
    <label for="note-title">Title
      <input type="text" name="note[title]" value="<%= note.title %>"><br>
    </label>

    <textarea name="note[body]" style="width: 600px; height: 400px;"><%= note.body %></textarea>

    <input type="hidden" name="_method" value="PUT">
    <%= render './layouts/form_auth' %>
    <input type="submit" value="Save Changes">
    <br>
  </form>

  <form action="<%= tags_url %>" method="post">

    <label for="tag-title">Tag
      <input type="text" name="tag[title]"><br>
    </label>
    <%= render './layouts/form_auth' %>
    <input type="hidden" name="tag[note_ids][]" value="<%= note.id %>">
    <input type="submit" value="Add Tag">
  <form>

  <% note.tags.each do |tag| %>
    <%= tag.title %>
  <% end %>
  <!-- <form action="<%= tags_url %>" method="POST">
    <label for="tag-title">Tag
      <input type="text" name="tag[title]"><br>
    </label>
    <input type="hidden" name="tag[note_id]" value="<%= note.id %>"></input>
    <%= render './layouts/form_auth' %>
    <input type="submit" value="Add Tag">
  </form> -->
<!-- <% else %> -->
<!-- <form action="<%= notes_url %>" method="POST">
  <label for="note-title">Title
    <input type="text" name="note[title]" value="Untitled"><br>
  </label>
  <textarea name="note[body]"></textarea>
  <input type="hidden" name="note[notebook_id]" value="<%= notebook.id %>">
  <%= render './layouts/form_auth' %>
  <input type="submit" value="Create Note">
</form> -->
<!-- <% end %> -->