config/routes.rb
Enclone::Application.routes.draw do
  resources :users, :except => [:index]
  resource :session, :only => [:new, :create, :destroy]
  resources :notebooks
  resources :notes
  resources :tags, :only => [:create, :index, :destroy, :show]

  root :to => "root#root"
end

app/views/layouts/_form_auth.html.erb
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

app/views/layouts/_user_form.html.erb
<form action="<%= action_url %>" method="POST">
  <label for="email">
  Email<input type="text" name="user[email]">
  </label>

  <label>
    Password<input type="password" name="user[password]">
  </label>

  <%= render "./layouts/form_auth" %>

  <% if hidden_method && hidden_method === "PUT" %>
    <%= '<input type="hidden" name="_method" value="PUT"' %>
  <% end %>
  <input type="submit" value="<%= button_val %>">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enclone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

</head>
<body>
  <!-- overflow hidden text-overflow: clip text overflow ellipsis -->
  <div class="header group">
    <nav class="nav-bar">
      <ul class="group">
        <% if logged_in? %>
          <li><%= current_user.email %></li>
          <li><%= button_to "Sign Out", session_url, :method => :delete %></li>
        <% else %>
        <!-- <li>< #link_to "Sign In", new_session_url ></li>
        <li>< #link_to "Sign Up", new_user_url ></li> -->
        <% end %>
      </ul>

    </nav>
  </div>

<%= yield %>
<% if flash[:errors] && flash[:errors].any? %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>
</body>
</html>